version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    labels:
      - 'benchmarks: skip'
  - package-ecosystem: npm
    directories:
      - /
      - /js/default
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@bytecodealliance/*'
      - dependency-name: '*componentize*'
      - dependency-name: '*quickjs*'
      - dependency-name: '*starlingmonkey*'
    labels:
      - 'benchmarks: skip'
  - package-ecosystem: cargo
    directories:
      - /
      - /crates/handler-rs
      - /crates/hyperlight-dummy-guest
    schedule:
      interval: weekly
    groups:
      cargo:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'hyperlight-*'
      - dependency-name: wasmtime
    labels:
      - 'benchmarks: skip'