[package]
name = "hyperlight-dummy-guest"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false
rust-version = "1.89"

[dependencies]
hyperlight-common = { version = "0.17.0", default-features = false }
hyperlight-guest = { version = "0.17.0", default-features = false }
hyperlight-guest-bin = { version = "0.17.0", default-features = false, features = ["macros"] }
